project:
  type: website

website:
  title: "Anastasia Soukhov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_cv.qmd
        text: About Me
      - href: publications.qmd
        text: Publications
      - href: R_highlights.qmd
        text: Research Highlights

format:
  html:
    theme: minty
    css: styles.css
    toc: true          # optional: table of contents
    toc-depth: 2
    code-fold: true    # fold long code blocks

editor: visual

